// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_bots': 'enable',
    'aws_bots_config': [{"name":"MakeAppointmentMOBILEHUB","alias":"$LATEST","description":"Bot to book a dentist appointment.","bot-template":"bot-appointments","commands-help":["I would like to book an appointment","Book an appointment","I would like to see the dentist","I would like to schedule a visit","Make appointment"],"region":"us-east-1"}],
    'aws_cognito_identity_pool_id': 'us-west-2:126e937b-d594-49cb-8687-172ff1e7ea30',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'opol-hosting-mobilehub-88837624',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dxqzdyq18er3w.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '3a4422ed89714fd49bbf5624151bd250',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '612164e1-6244-4729-8d0a-94844a7d341b',
    'aws_project_name': 'opol5',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'opol-mobilehub-88837624',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_hCVnLcSMS',
    'aws_user_pools_web_client_id': '777osdop41qq005c4f4977nbcq',
}

export default awsmobile;
